### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by cre8** [sms77io/js-client#14]
I am using Node version 16 with node-fetch installed and still getting the error in my typescript project:
```
ReferenceError: fetch is not defined
    at Sms77Client.<anonymous> (/root/trustsuite/node_modules/sms77-client/dist/Sms77Client.umd.js:177:25)
    at step (/root/trustsuite/node_modules/sms77-client/dist/Sms77Client.umd.js:47:23)
    at Object.next (/root/trustsuite/node_modules/sms77-client/dist/Sms77Client.umd.js:28:53)
    at /root/trustsuite/node_modules/sms77-client/dist/Sms77Client.umd.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/root/trustsuite/node_modules/sms77-client/dist/Sms77Client.umd.js:18:12)
    at Sms77Client.BaseClient.request (/root/trustsuite/node_modules/sms77-client/dist/Sms77Client.umd.js:123:16)
    at Sms77Client.<anonymous> (/root/trustsuite/node_modules/sms77-client/dist/Sms77Client.umd.js:105:51)
    at step (/root/trustsuite/node_modules/sms77-client/dist/Sms77Client.umd.js:47:23)
    at Object.next (/root/trustsuite/node_modules/sms77-client/dist/Sms77Client.umd.js:28:53)
```

**Comment by cre8** [comment]
Using fetch with a `2.X` version gives me the same error. I tried downgrading because the version 3 requires the package to support esm. Also installing `@types/node-fetch` had no effect.

**Comment by matthiez** [comment]
Hi, did you try to assign fetch to `globalThis`?

I just tried it with the following code and it works fine.

```javascript
import fetch from 'node-fetch'
import Sms77Client from './dist/Sms77Client.umd.js'
globalThis.fetch = fetch;
console.log('NodeJS version: ', process.version)
const apiKey = 'InsertYourApiKey'
const sms77Client = new Sms77Client(apiKey, 'js-test')
const balance = await sms77Client.balance()
console.log('balance: ', balance)
```

The output is:
```
NodeJS version:  v16.19.0
balance:  49.658
```

**Comment by cre8** [comment]
@matthiez no I didn't since the docs told me for a version greater than 12 I do not need it:
```
// const globalThis = require('globalthis')(); // uncomment if NodeJS < NodeJS versions < 12
```

**Comment by matthiez** [comment]
@cre8 
Yes, because older node versions don't have globalThis implementation.
The next line still applies to all node environments:
`globalThis.fetch = require('node-fetch').default; // uncomment in NodeJS environments`
